//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dostawy
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Dostawy()
        {
            this.SzczegolyDostawy = new HashSet<SzczegolyDostawy>();
        }
    
        public int IdDostawy { get; set; }
        public Nullable<int> IdKontrahentow { get; set; }
        public Nullable<System.DateTime> DataDostawy { get; set; }
        public string Status { get; set; }
    
        public virtual Kontrahenci Kontrahenci { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczegolyDostawy> SzczegolyDostawy { get; set; }
    }
}
