//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Faktury
    {
        public int IdFaktury { get; set; }
        public Nullable<int> IdZamowienia { get; set; }
        public Nullable<System.DateTime> DataWystawienia { get; set; }
        public Nullable<decimal> KwotaCalkowita { get; set; }
        public Nullable<System.DateTime> TerminPlatnosci { get; set; }
        public string NumerFaktury { get; set; }
        public Nullable<int> IdPracownika { get; set; }
        public string TypFaktury { get; set; }
        public Nullable<bool> StatusFaktury { get; set; }
        public string Waluta { get; set; }
    
        public virtual Zamowienia Zamowienia { get; set; }
        public virtual Pracownicy Pracownicy { get; set; }
    }
}
