//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Kontrahenci
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Kontrahenci()
        {
            this.Dostawy = new HashSet<Dostawy>();
        }
    
        public int IdKontrahenta { get; set; }
        public string Nazwa { get; set; }
        public string Kontakt { get; set; }
        public string Email { get; set; }
        public string Telefon { get; set; }
        public Nullable<int> IdAdresu { get; set; }
        public string NIP { get; set; }
        public string Regon { get; set; }
        public string TypKontrahenta { get; set; }
        public string StatusKontrahenta { get; set; }
        public Nullable<System.DateTime> DataUtworzenia { get; set; }
    
        public virtual Adres Adres { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Dostawy> Dostawy { get; set; }
    }
}
