//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produkty
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produkty()
        {
            this.Promocje = new HashSet<Promocje>();
            this.SzczegolyZamowienia = new HashSet<SzczegolyZamowienia>();
            this.SzczegolyDostawy = new HashSet<SzczegolyDostawy>();
            this.ZapasyMagazynowe = new HashSet<ZapasyMagazynowe>();
        }
    
        public int IdProduktu { get; set; }
        public string Nazwa { get; set; }
        public Nullable<int> IdKategori { get; set; }
        public string Producent { get; set; }
        public string NumerCzesci { get; set; }
        public Nullable<decimal> Cena { get; set; }
        public string Opis { get; set; }
        public bool Dostepny { get; set; }
    
        public virtual Kategorie Kategorie { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Promocje> Promocje { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SzczegolyDostawy> SzczegolyDostawy { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ZapasyMagazynowe> ZapasyMagazynowe { get; set; }
    }
}
