//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVVMFirma.Models.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SklepSamochodowyEntities : DbContext
    {
        public SklepSamochodowyEntities()
            : base("name=SklepSamochodowyEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Adres> Adres { get; set; }
        public virtual DbSet<Dostawy> Dostawy { get; set; }
        public virtual DbSet<Faktury> Faktury { get; set; }
        public virtual DbSet<HistoriaLogowania> HistoriaLogowania { get; set; }
        public virtual DbSet<Kategorie> Kategorie { get; set; }
        public virtual DbSet<Klienci> Klienci { get; set; }
        public virtual DbSet<Kontrahenci> Kontrahenci { get; set; }
        public virtual DbSet<Magazyny> Magazyny { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Produkty> Produkty { get; set; }
        public virtual DbSet<Promocje> Promocje { get; set; }
        public virtual DbSet<Reklamacje> Reklamacje { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<SzczegolyDostawy> SzczegolyDostawy { get; set; }
        public virtual DbSet<SzczegolyZamowienia> SzczegolyZamowienia { get; set; }
        public virtual DbSet<Zamowienia> Zamowienia { get; set; }
        public virtual DbSet<ZapasyMagazynowe> ZapasyMagazynowe { get; set; }
    }
}
